// Generated by https://quicktype.io

export interface UserResponse {
    usuario: Usuario[];
}

export interface Usuario {
    id:       number;
    name:     string;
    username: string;
    email:    string;
    phone:    string;
    website:  string;
    address:  Address;
    company:  Company;
}

export interface Address {
    street:  string;
    suite:   string;
    city:    string;
    zipcode: null | string;
    geo:     Geo;
}

export interface Geo {
    lat:  string;
    long: string;
}

export interface Company {
    name:        string;
    catchPhrase: string;
    bs:          string;
}
